#!/usr/bin/env ruby

require "socket"

files = ARGV

# Handle no arguments by reading stdin
files[0] ||= "-"

exit_code = 0

[$stdout, $stderr].each do |io|
  io.sync = true
  io.flush
end

files.each do |path|
  if path == "-"
    $stdout.print($stdin.read)
    next
  end

  unless File.exist?(path)
    $stderr.puts "cat: #{path}: No such file or directory"
    exit_code = 1
    next
  end

  if File.socket?(path)
    UNIXSocket.open(path) do |sock|
      IO.copy_stream(sock, $stdout)
    end
  else
    $stdout.print(File.read(path))
  end
end

exit(exit_code)
